name: tfplan
base: core22
version: '0.1.0'
summary: A minimal CLI tool to format Terraform plan output
description: |
  A minimal CLI tool to format Terraform plan output in a beautiful, 
  human-readable format with expandable HTML output.

grade: stable
confinement: strict

apps:
  tfplan:
    command: bin/tfplan
    plugs:
      - home
      - network

parts:
  tfplan:
    plugin: rust
    source: .
    build-packages:
      - build-essential
    stage-packages:
      - libc6